name: Feature Request
description: Suggest a new feature or enhancement for Forge
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your needs.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point does it address?
      placeholder: I need Forge to help me with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like Forge to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you tried or considered?
      placeholder: |
        - Currently doing manually
        - Tried using other tools

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my use of Forge
      default: 1

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        - When designing a new feature, I need...
        - When distilling sessions, I want...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component should this feature be added to?
      options:
        - VSCode Extension
        - MCP Server
        - Both
        - New Component
      default: 0

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples, or additional details

